steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'beta',
    'functions',
    'deploy',
    '${_TARGET_CLOUD_FUNCTIONS}',
    '--source',
    'https://source.developers.google.com/projects/$PROJECT_ID/repos/$REPO_NAME/moveable-aliases/$BRANCH_NAME',
    '--runtime',
    'nodejs8',
    '--memory',
    '1024MB',
    '--region',
    'asia-northeast1',
    '--entry-point',
    'getScreenShot',
    '--trigger-http',
    '--update-env-vars',
    'UPLOAD_STORAGE_BUCKET=${_UPLOAD_STORAGE_BUCKET}',
  ]
- name: 'gcr.io/cloud-builders/gsutil'
  args: [
    'lifecycle',
    'set',
    'lifecycle.json',
    'gs://${_UPLOAD_STORAGE_BUCKET}',
  ]